import { StyleSheet } from 'react-native';
import { palette, typography, spacing, radius } from './theme';

export const debriefingActivityIndicatorColor = palette.matrixGreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: palette.bgPrimary,
  },
  content: {
    flexGrow: 1,
    padding: spacing.xl,
    paddingBottom: spacing.xxl * 2,
  },

  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  loadingText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxl,
    color: palette.matrixGreen,
    marginBottom: spacing.xl,
    letterSpacing: 2,
  },
  loadingSubtext: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textMuted,
    marginTop: spacing.lg,
  },

  revealContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  revealPrimary: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxxl,
    color: palette.matrixGreen,
    textAlign: 'center',
    marginBottom: spacing.xxl,
    letterSpacing: 3,
  },
  revealSecondary: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxl,
    color: palette.alertRed,
    textAlign: 'center',
    letterSpacing: 2,
  },

  title: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxxl,
    color: palette.matrixGreen,
    textAlign: 'center',
    marginBottom: spacing.md,
    letterSpacing: 2,
  },
  subtitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textMuted,
    textAlign: 'center',
    marginBottom: spacing.sm,
    letterSpacing: 1,
  },
  subtitleNoteSlate: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.terminalSlate,
    textAlign: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    letterSpacing: 1,
  },
  subtitleNoteWarning: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.warningAmber,
    textAlign: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    letterSpacing: 1,
  },
  scroll: {
    flex: 1,
  },

  threatBanner: {
    backgroundColor: palette.bgCard,
    borderWidth: 3,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginVertical: spacing.xl,
    alignItems: 'center',
    shadowColor: palette.alertRed,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  threatLabel: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.textMuted,
    marginBottom: spacing.sm,
    letterSpacing: 1,
  },
  threatValue: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxxl,
    fontWeight: typography.fontWeights.bold,
    marginBottom: spacing.sm,
    letterSpacing: 3,
  },
  threatScore: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.lg,
    color: palette.textSecondary,
    letterSpacing: 2,
  },

  warningCard: {
    backgroundColor: palette.bgCard,
    borderWidth: 2,
    borderColor: palette.borderDanger,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.xl,
  },
  warningTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xl,
    color: palette.alertRed,
    textAlign: 'center',
    marginBottom: spacing.md,
    letterSpacing: 2,
  },
  warningText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  warningTextCritical: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.alertRed,
    textAlign: 'center',
    lineHeight: 22,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },

  card: {
    backgroundColor: palette.bgCard,
    borderWidth: 2,
    borderColor: palette.borderPrimary,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.lg,
  },
  cardTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.lg,
    color: palette.matrixGreen,
    marginBottom: spacing.md,
    letterSpacing: 1,
  },

  dataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: palette.borderSecondary,
    marginBottom: spacing.sm,
  },
  dataLabel: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textSecondary,
  },
  dataValue: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.matrixGreen,
    fontWeight: typography.fontWeights.bold,
  },
  dataValueSolo: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.matrixGreen,
    fontWeight: typography.fontWeights.bold,
    textAlign: 'left',
  },

  fingerprintGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  fingerprintItem: {
    width: '48%',
    backgroundColor: palette.bgSecondary,
    padding: spacing.md,
    borderRadius: radius.sm,
    marginBottom: spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: palette.matrixGreen,
  },
  fingerprintLabel: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xs,
    color: palette.textMuted,
    marginBottom: 4,
  },
  fingerprintValue: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.matrixGreen,
    fontWeight: typography.fontWeights.bold,
  },

  logContainer: {
    maxHeight: 200,
    backgroundColor: palette.bgSecondary,
    borderRadius: radius.sm,
    padding: spacing.md,
  },
  logEntry: {
    borderLeftWidth: 2,
    borderLeftColor: palette.matrixGreen,
    paddingLeft: spacing.sm,
    marginBottom: spacing.md,
  },
  logTimestamp: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xs,
    color: palette.textMuted,
    marginBottom: 4,
  },
  logData: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.textSecondary,
  },
  logMore: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.textMuted,
    textAlign: 'center',
    marginTop: spacing.md,
    fontStyle: 'italic',
  },

  evidenceImage: {
    width: '100%',
    height: 200,
    borderRadius: radius.sm,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: palette.borderPrimary,
  },
  evidenceCaption: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.alertRed,
    textAlign: 'center',
    letterSpacing: 1,
  },

  toggleButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.matrixGreen,
    padding: spacing.md,
    borderRadius: radius.sm,
    marginBottom: spacing.lg,
  },
  toggleButtonRetry: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.matrixGreen,
    padding: spacing.md,
    borderRadius: radius.sm,
    marginTop: spacing.md,
    marginBottom: spacing.lg,
  },
  toggleButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.matrixGreen,
    textAlign: 'center',
    letterSpacing: 1,
  },

  finalCard: {
    backgroundColor: palette.bgCard,
    borderWidth: 3,
    borderColor: palette.alertRed,
    borderRadius: radius.md,
    padding: spacing.xl,
    marginVertical: spacing.xl,
    shadowColor: palette.alertRed,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
  },
  finalTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxl,
    color: palette.alertRed,
    textAlign: 'center',
    marginBottom: spacing.lg,
    letterSpacing: 2,
  },
  finalText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  finalTextCritical: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.alertRed,
    textAlign: 'center',
    lineHeight: 22,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },

  restartButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.matrixGreen,
    padding: spacing.lg,
    borderRadius: radius.sm,
    marginBottom: spacing.xxl,
    shadowColor: palette.matrixGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  restartButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.matrixGreen,
    textAlign: 'center',
    letterSpacing: 1,
  },

  errorText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.alertRed,
    textAlign: 'center',
    marginTop: spacing.lg,
  },
});

export default styles;
