import { StyleSheet } from 'react-native';
import { palette, typography, spacing, radius } from './theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: palette.bgPrimary,
  },

  header: {
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: palette.borderPrimary,
    backgroundColor: palette.bgCard,
  },
  headerTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxl,
    color: palette.matrixGreen,
    textAlign: 'center',
    marginBottom: spacing.sm,
    letterSpacing: 2,
  },
  headerInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerAgent: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.textMuted,
  },
  headerStatus: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.textMuted,
  },
  headerSyncStrip: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xs,
    textAlign: 'center',
    marginTop: spacing.sm,
    letterSpacing: 0.5,
  },

  briefingScrollView: {
    flex: 1,
  },
  briefingContainer: {
    flexGrow: 1,
    padding: spacing.xl,
    paddingBottom: spacing.xxl * 2,
  },
  briefingHeader: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxxl,
    color: palette.matrixGreen,
    textAlign: 'center',
    marginBottom: spacing.xxl,
    letterSpacing: 2,
  },
  briefingCard: {
    backgroundColor: palette.bgCard,
    borderWidth: 2,
    borderColor: palette.borderPrimary,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.lg,
  },
  briefingAgentLabel: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.textMuted,
    marginBottom: 4,
  },
  briefingAgentName: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxl,
    color: palette.matrixGreen,
    marginBottom: spacing.md,
    letterSpacing: 2,
  },
  briefingStatus: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textSecondary,
  },
  briefingTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.lg,
    color: palette.matrixGreen,
    marginBottom: spacing.md,
    letterSpacing: 1,
  },
  briefingText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textSecondary,
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  briefingButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.matrixGreen,
    padding: spacing.lg,
    borderRadius: radius.sm,
    marginTop: spacing.lg,
    shadowColor: palette.matrixGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  briefingButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.lg,
    color: palette.matrixGreen,
    textAlign: 'center',
    letterSpacing: 1,
  },

  taskScrollView: {
    flex: 1,
  },
  taskContainer: {
    flexGrow: 1,
    padding: spacing.lg,
    paddingBottom: spacing.xxl * 2,
  },

  taskCard: {
    backgroundColor: palette.bgCard,
    borderWidth: 2,
    borderColor: palette.borderPrimary,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.lg,
  },
  taskTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xl,
    color: palette.matrixGreen,
    marginBottom: spacing.sm,
    letterSpacing: 1,
    textAlign: 'center',
  },
  taskMetaRow: {
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  taskMetaText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xs,
    color: palette.textMuted,
    letterSpacing: 1,
  },
  taskObjective: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textSecondary,
    lineHeight: 22,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  taskInstructions: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.sm,
    color: palette.textSecondary,
    lineHeight: 20,
    textAlign: 'center',
  },

  stealthCard: {
    backgroundColor: palette.bgCard,
    borderWidth: 2,
    borderColor: palette.borderPrimary,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.lg,
  },
  stealthLabel: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.matrixGreen,
    marginBottom: spacing.sm,
    letterSpacing: 1,
    textAlign: 'center',
  },
  stealthMeterContainer: {
    height: 24,
    backgroundColor: palette.bgPrimary,
    borderWidth: 1,
    borderColor: palette.borderPrimary,
    borderRadius: radius.sm,
    overflow: 'hidden',
    marginBottom: spacing.sm,
  },
  stealthMeterFill: {
    height: '100%',
    backgroundColor: palette.matrixGreen,
    shadowColor: palette.matrixGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
  },
  stealthValue: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxl,
    color: palette.matrixGreen,
    textAlign: 'center',
    fontWeight: typography.fontWeights.bold,
  },
  taskButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.matrixGreen,
    padding: spacing.lg,
    borderRadius: radius.sm,
    marginBottom: spacing.lg,
    shadowColor: palette.matrixGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  taskButtonDisabled: {
    borderColor: palette.textMuted,
    shadowOpacity: 0,
  },
  taskButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.lg,
    color: palette.matrixGreen,
    textAlign: 'center',
    letterSpacing: 1,
  },

  progressIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  progressDot: {
    width: 40,
    height: 8,
    backgroundColor: palette.bgCard,
    borderWidth: 1,
    borderColor: palette.borderSecondary,
    borderRadius: radius.sm,
  },
  progressDotComplete: {
    backgroundColor: palette.matrixGreen,
    borderColor: palette.matrixGreen,
    shadowColor: palette.matrixGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  progressDotActive: {
    borderColor: palette.matrixGreen,
    borderWidth: 2,
  },

  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'space-between',
    padding: spacing.xl,
  },
  cameraTitle: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxl,
    color: palette.matrixGreen,
    textAlign: 'center',
    marginTop: spacing.xxl,
    letterSpacing: 2,
  },
  cameraHint: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.textSecondary,
    textAlign: 'center',
    backgroundColor: palette.bgCard,
    padding: spacing.md,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: palette.borderPrimary,
  },
  cameraButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.xxl,
  },
  cameraButtonCancel: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.textMuted,
    padding: spacing.lg,
    borderRadius: radius.sm,
    flex: 1,
    marginRight: spacing.md,
  },
  cameraButtonCapture: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.matrixGreen,
    padding: spacing.lg,
    borderRadius: radius.sm,
    flex: 1,
    marginLeft: spacing.md,
    shadowColor: palette.matrixGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  cameraButtonDisabled: {
    borderColor: palette.textMuted,
    shadowOpacity: 0,
  },
  cameraButtonText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.md,
    color: palette.matrixGreen,
    textAlign: 'center',
    letterSpacing: 1,
  },

  completeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  completeHeader: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.xxxl,
    color: palette.matrixGreen,
    textAlign: 'center',
    marginBottom: spacing.xxl,
    letterSpacing: 2,
  },
  completeText: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizes.lg,
    color: palette.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.md,
    letterSpacing: 1,
  },
});
