export const LOCATION_UPDATE_INTERVAL_MS = 15000;
export const BACKGROUND_DISTANCE_INTERVAL_METERS = 10;
export const LOCATION_TELEMETRY_DEDUPE_WINDOW_MS = LOCATION_UPDATE_INTERVAL_MS;
export const LOCATION_OUTBOX_FLUSH_BATCH_SIZE = 20;
